### ISSUE TITLE
Tab do not re-snap to windows in Chromium 97 update

### ISSUE THREAD

**Issue by ramesh45345** [flathub/org.chromium.Chromium#190]
In the recent Chromium 97 update, tabs when separated from their parent window are not able to be re-snapped into a window once dragged off. A visual of this issue is provided here (commit: `144d890316a254495179cea41e6038dc1b720d08bfdfcfb564958765983cfa6c`): 
https://user-images.githubusercontent.com/6318224/149637770-5bbe41e5-286b-4f93-a6ea-0ae2fca9d6ac.mp4

Expected Behavior is shown here (commit: `3c3c27b8c5e5c7e01fe0d879b626a4f1e26aba9deb51ccd2ce85d7ab56ba5a4c`): 
https://user-images.githubusercontent.com/6318224/149637783-c86d9d98-baf6-4970-89fe-a1cdc8e7d9cd.mp4

Here are the steps to reproduce the issue:
1. Install the flatpak using the command: `flatpak install --or-update flathub org.chromium.Chromium`. At the time of this report, commit `144d890316a254495179cea41e6038dc1b720d08bfdfcfb564958765983cfa6c` is installed.
2. Ensure any custom permissions are reset / set to defaults via flatseal.
3. Ensure a clean profile is being used: `rm -rf ~/.var/app/org.chromium.Chromium/`
4. Start Chromium, and observe the above issue when trying to re-integrate a tab into a window.
5. Close chromium, and downgrade chromium version using the following command: `sudo flatpak update org.chromium.Chromium --commit=3c3c27b8c5e5c7e01fe0d879b626a4f1e26aba9deb51ccd2ce85d7ab56ba5a4c`
6. Re-open chromium, and observe tab integration into a window works properly.

The issue is observed in the following version:
```
        ID: org.chromium.Chromium
       Ref: app/org.chromium.Chromium/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 118.0 MB
 Installed: 302.6 MB
   Runtime: org.freedesktop.Platform/x86_64/21.08
       Sdk: org.freedesktop.Sdk/x86_64/21.08

    Commit: 144d890316a254495179cea41e6038dc1b720d08bfdfcfb564958765983cfa6c
    Parent: 3c3c27b8c5e5c7e01fe0d879b626a4f1e26aba9deb51ccd2ce85d7ab56ba5a4c
   Subject: Update patches for Chromium 97.0.4692.71 (25dfb699)
      Date: 2022-01-05 22:24:49 +0000
   History: 
```
The expected behavior is last seen working properly with this verison:
```
    Commit: 3c3c27b8c5e5c7e01fe0d879b626a4f1e26aba9deb51ccd2ce85d7ab56ba5a4c
   Subject: Fix issue #184 (7199e0bc)
      Date: 2022-01-01 01:10:04 +0000
```

Information about the system environment:
```
$ uname -a
Linux Packer-Fedora-kvm 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 35 (Thirty Five)
Release:        35
Codename:       ThirtyFive
$ plasmashell --version
plasmashell 5.23.4
```

All testing was done under X11. The videos were taken in a virtual machine, but this same behavior has been observed on host machines as well. Although the machine is Fedora 35, I have observed the same issue on a fresh install of Arch Linux. I've also obersved the issue on several machines. Is this related to flatpak permissions? Or is this user error on my part, or some sort of configuration issue on my systems? The problem does seem to go away when I switch to the older flatpak commit, with no other changes or steps in between.

Its also worth noting that I tested the native version of Chromium 97 installed through the fedora repositories, and tab re-integration does work properly. Therefore, I believe this is a specific issue for the flatpak version.

Please let me know if I am missing some information, or if I can add to the detail of this report in some way.
